---
name: File-Find-Object
version: 0.1.7
author: []
abstract: An object oriented File::Find replacement
license: perl
resources:
  license: http://dev.perl.org/licenses/
requires:
  Carp: 0
  Class::XSAccessor: 0
  Fcntl: 0
  File::Spec: 0
  List::Util: 0
  base: 0
  strict: 0
  warnings: 0
build_requires:
  File::Path: 0
  Test::More: 0
provides:
  File::Find::Object:
    file: lib/File/Find/Object.pm
    version: 0.1.7
  File::Find::Object::Base:
    file: lib/File/Find/Object/Base.pm
  File::Find::Object::DeepPath:
    file: lib/File/Find/Object.pm
  File::Find::Object::PathComp:
    file: lib/File/Find/Object/PathComp.pm
  File::Find::Object::Result:
    file: lib/File/Find/Object/Result.pm
  File::Find::Object::TopPath:
    file: lib/File/Find/Object.pm
generated_by: Module::Build version 0.31
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.2.html
  version: 1.2
