---
name: File-Find-Object
version: 0.2.2
author: []
abstract: An object oriented File::Find replacement
license: perl
resources:
  Repository: svn+ssh://nanardon.zarb.org/home/svn/File-Find-Object/trunk
  homepage: http://www.shlomifish.org/open-source/projects/File-Find-Object/
  license: http://www.perlfoundation.org/artistic_license_2_0
requires:
  Carp: 0
  Class::XSAccessor: 0
  Fcntl: 0
  File::Spec: 0
  List::Util: 0
  base: 0
  strict: 0
  warnings: 0
build_requires:
  File::Path: 0
  Test::More: 0
provides:
  File::Find::Object:
    file: lib/File/Find/Object.pm
    version: 0.2.2
  File::Find::Object::Base:
    file: lib/File/Find/Object/Base.pm
  File::Find::Object::DeepPath:
    file: lib/File/Find/Object.pm
  File::Find::Object::PathComp:
    file: lib/File/Find/Object/PathComp.pm
  File::Find::Object::Result:
    file: lib/File/Find/Object/Result.pm
  File::Find::Object::TopPath:
    file: lib/File/Find/Object.pm
generated_by: Module::Build version 0.33
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
keywords:
  - alternative-to-core
  - directories
  - directory
  - directory-traversal
  - directory-tree
  - directory-trees
  - file
  - file-find
  - find
  - instance
  - instantiated
  - instantiation
  - iterative
  - object
  - object-oriented
  - oop
  - prune
  - traversal
  - traverse
  - tree
