#!/usr/bin/perl

# $Id: tree 84 2007-02-02 16:29:55Z shlomif $

use strict;
use warnings;
use File::Find::Object;
use Getopt::Long;

my %options;

GetOptions(
    'd' => \$options{depth},
    'n' => \$options{nonet},
    'f' => \$options{nocrossfs},
    'l' => \$options{followlink},
);

my $tree = File::Find::Object->new({ %options }, @ARGV);

while (my $r = $tree->next()) {
    print $r ."\n";
}
